server:
  port: 0 # will run on random port



eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8010/eureka"

  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    hostname: localhost   # useful to overcome java.net.UnknownHostException: Failed to resolve  [A(1), AAAA(28)]


spring:
  application:
    name: demo-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # configuration needed for validating JWT token against our Keycloak server
          issuer-uri: http://localhost:8080/realms/adjoda-dev-realm

          #Since JWT is signed and we need to verify its signature, we set the jwk-set-uri property to a Keycloak endpoint with
          # the required data for JWT signature verification.
          jwk-set-uri: http://localhost:8080/realms/adjoda-dev-realm/protocol/openid-connect/certs