
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8010/eureka"


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://demo-resource-server   #spring.application.name
          predicates:
            - Path=/api/v1/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: lb://album-resource-server  #spring.application.name
          predicates:
            - Path=/api/v1/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: lb://photos-resource-server  #spring.application.name
          predicates:
            - Path=/api/v1/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie