
server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie